# Retrieve genes sequence around the TSS (transcript start site) with its median gene expression

This notebook is designed to retrieve gene sequences and their corresponding median expression levels. To make it work, you'll need to adjust the file paths for the following three required files:

1. **Gene Expression Data**: A file from GTEx containing median gene expression levels.
2. **Human Genome Sequence**: A file from NCBI containing the human genome sequence.
3. **Genome Annotations**: A file from NCBI with annotations for the human genome.

Once you've set the correct paths, the notebook will be ready to use. Ctrl+f "path_to_change" to find the paths

## Genes sequence

To begin, we should have the IDs of the genes for which we want to retrieve sequences. For this, we need to download the complete human genome from NCBI. Here is the link for GRCh38.p14: [GRCh38.p14 Genome](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000001405.40/). Make sure that there isn't a more recent version of the human genome available, as it is constantly being updated and corrected.  
<br>
Download **GenBank** format only, and ensure that you select **genome sequences** as well as **sequence and annotations**.  
<br>
Once it's downloaded, unzip the file. You'll need two files: one that contains the gene sequences, and the other that contains the annotations. To retrieve the sequence of a specific gene, you'll need information on its start, end, strand, chromosome and gene ID.  
<br>
The file containing the annotations is named `genomic.gff`, and the one containing the gene sequences is named `GCF_000001405.40_GRCh38.p14_genomic.fna`. <br>

### Annotations table

You can see in the following the columns that are in the annotations table for all the genes you can filter the dataframe based on your preferences for example if you want only protein_coding genes you filter your dataframe based on the column **gene_biotype**

In [ ]:
!pip install gtfparse

In [3]:
from gtfparse import read_gtf

# returns GTF with essential columns such as "feature", "seqname", "start", "end"
# alongside the names of any optional keys which appeared in the attribute column path_to_change
gene_annotations = read_gtf("../ncbi_dataset/data/GCF_000001405.40/genomic.gtf")

gene_annotations = gene_annotations.to_pandas()

gene_annotations = gene_annotations[gene_annotations["feature"]=="gene"]

gene_annotations["GENE_ID"] = gene_annotations["gene_id"].apply(lambda x: x.split(".")[0])
gene_annotations.rename(columns = {"gene_id" : "last_gene_id"}, inplace = True)

print("gene_annotation columns : \n")
print(gene_annotations.columns)
print("\n")
print("example of the annotations of a gene : \n")
print(gene_annotations.iloc[0])

INFO:root:Extracted GTF attributes: ['gene_id', 'transcript_id', 'db_xref', 'description', 'gbkey', 'gene', 'gene_biotype', 'pseudo', 'product', 'transcript_biotype', 'exon_number', 'gene_synonym', 'model_evidence', 'tag', 'protein_id', 'experiment', 'inference', 'note', 'part', 'exception', 'isoform', 'anticodon', 'partial', 'The', 'transl_except', 'non-AUG', 'standard_name', 'deleted', 'source', 'similar', 'substituted', 'transferase', 'codons', '12S', '16S', 'transl_table', 'ATPase']

gene_annotation columns :

Index(['seqname', 'source', 'feature', 'start', 'end', 'score', 'strand',
       'frame', 'last_gene_id', 'transcript_id', 'db_xref', 'description',
       'gbkey', 'gene', 'gene_biotype', 'pseudo', 'product',
       'transcript_biotype', 'exon_number', 'gene_synonym', 'model_evidence',
       'tag', 'protein_id', 'experiment', 'inference', 'note', 'part',
       'exception', 'isoform', 'anticodon', 'partial', 'The', 'transl_except',
       'non-AUG', 'standard_name', 'deleted', 'similar', 'substituted',
       'transferase', 'codons', '12S', '16S', 'transl_table', 'ATPase',
       'GENE_ID'],
      dtype='object')


example of the annotations of a gene :

seqname                                   NC_000001.11
source
feature                                           gene
start                                            11874
end                                              14409
score                                              NaN
strand                                               +
frame                                                0
last_gene_id                                   DDX11L1
transcript_id
db_xref               GeneID:100287102,HGNC:HGNC:37102
description                                 DEAD/H-box
gbkey                                             Gene
gene                                           DDX11L1
gene_biotype                    transcribed_pseudogene
pseudo                                            true
product
transcript_biotype
exon_number
gene_synonym
model_evidence
tag
protein_id
experiment
inference
note
part
exception
isoform
anticodon
partial
The
transl_except
non-AUG
standard_name
deleted
similar
substituted
transferase
codons
12S
16S
transl_table
ATPase
GENE_ID                                        DDX11L1
Name: 0, dtype: object

### Retrieve the Sequence

Change here these two top varibales to retrieve the frame sequence of the gene around the TSS as you prefere

In [4]:
sequence_length_left = 0
sequence_length_right = 2000


import pandas as pd
from Bio import SeqIO

# Charger le fichier FASTA et stocker les séquences dans un dictionnaire path_to_change
fasta_file = "../ncbi_dataset/data/GCF_000001405.40/GCF_000001405.40_GRCh38.p14_genomic.fna"
chromosome_sequences = {}
for record in SeqIO.parse(fasta_file, "fasta"):
    chromosome_sequences[record.id] = str(record.seq)

# Charger le DataFrame
df = gene_annotations

# Définir la longueur de la séquence à extraire (par exemple, 5000 bases de chaque côté)

# Fonction pour extraire la séquence centrée autour de 'start' ou 'end' basé sur 'strand'
def get_centered_sequence(row):
    chromosome = row['seqname']
    if row['strand'] == '+':
        center = row['start']
    else:
        center = row['end']
    
    seq = chromosome_sequences.get(chromosome, "")
    if seq:
        start_idx = max(0, center - sequence_length_left)
        end_idx = min(len(seq), center + sequence_length_right)
        return seq[start_idx-1:end_idx]
    return ""

# Ajouter la nouvelle colonne avec les séquences extraites
df['sequence'] = df.apply(get_centered_sequence, axis=1)

def reverse_complement(sequence):
    # Dictionnaire de complémentarité des nucléotides
    complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C',
                  'a': 't', 't': 'a', 'c': 'g', 'g': 'c',
                  'N': 'N', 'n': 'n'}  # 'N' reste 'N', 'n' reste 'n'
    
    # Générer la séquence complémentaire
    complement_sequence = ''.join(complement.get(base, base) for base in sequence)
    
    # Inverser la séquence complémentaire
    reverse_complement_sequence = complement_sequence[::-1]
    
    return reverse_complement_sequence

df['sequence_'] = df.apply(lambda row: reverse_complement(row['sequence'].upper()) if row['strand'] == '-' else row['sequence'], axis=1)
df.drop(columns = ["sequence"], inplace = True)
df.rename(columns = {"sequence_" : "sequence"}, inplace = True)

In [5]:
df.columns

Index(['seqname', 'source', 'feature', 'start', 'end', 'score', 'strand',
       'frame', 'last_gene_id', 'transcript_id', 'db_xref', 'description',
       'gbkey', 'gene', 'gene_biotype', 'pseudo', 'product',
       'transcript_biotype', 'exon_number', 'gene_synonym', 'model_evidence',
       'tag', 'protein_id', 'experiment', 'inference', 'note', 'part',
       'exception', 'isoform', 'anticodon', 'partial', 'The', 'transl_except',
       'non-AUG', 'standard_name', 'deleted', 'similar', 'substituted',
       'transferase', 'codons', '12S', '16S', 'transl_table', 'ATPase',
       'GENE_ID', 'sequence'],
      dtype='object')

### Result

we have now our dataframe with the genes and their corresponding sequence

In [8]:
df[['seqname', 'start', 'end', 'strand', 'last_gene_id', 'sequence', 'gene_biotype']]

,seqname,start,end,strand,last_gene_id,sequence,gene_biotype
0,NC_000001.11,11874,14409,+,DDX11L1,CTTGCCGTCAGCCTTTTCTTTGACCTCTTCTTTCTGTTCATGTGTA...,transcribed_pseudogene
5,NC_000001.11,14362,29370,-,WASH7P,AAATCCCATTACAAATGGGGTGACTGAAGCTCCATTCATGGCTTGC...,transcribed_pseudogene
18,NC_000001.11,17369,17436,-,MIR6859-1,ACCATCCCACATCCTCCCCCTCCCTTTCCTCATGAACCCCAGTCGC...,miRNA
25,NC_000001.11,29774,35418,+,MIR1302-2HG,tgccctccagccctaCGCCTTGACCCGCTTTCCTGCGTCTCTCAGC...,lncRNA
30,NC_000001.11,30366,30503,+,MIR1302-2,GGATGCCCAGCTagtttgaattttagataaacaacgAATAATTTCG...,miRNA
...,...,...,...,...,...,...,...
4693791,NC_012920.1,14149,14673,-,ND6,CATCGTGATGTCTTATTTAAGGGGAACGTGTGGGCTATTTAGGCTT...,protein_coding
4693797,NC_012920.1,14674,14742,-,TRNE,CATCGTGATGTCTTATTTAAGGGGAACGTGTGGGCTATTTAGGCTT...,tRNA
4693800,NC_012920.1,14747,15887,+,CYTB,ATGACCCCAATACGCAAAACTAACCCCCTAATAAAATTAATTAACC...,protein_coding
4693806,NC_012920.1,15888,15953,+,TRNT,GTCCTTGTAGTATAAACTAATACACCAGTCTTGTAAACCGGAGATG...,tRNA
4693809,NC_012920.1,15956,16023,-,TRNP,CATCGTGATGTCTTATTTAAGGGGAACGTGTGGGCTATTTAGGCTT...,tRNA

## Gene expression data

Now that we have our gene sequences, we need to obtain gene expression data to train a model that learns to associate gene sequences with their corresponding expressions.

For each gene, the expression data can vary based on the individual and the tissue where the measurement is taken. To simplify this, we aggregate all measurements to produce a single value for each gene per tissue. In this example, we'll use data from the pituitary tissue, but you can choose any tissue you prefer.

We retrieve the data from GTEx. Below is the link to a file that contains the median expression for each gene across various tissues:

- [GTEx Download Link](https://gtexportal.org/home/downloads/adult-gtex/bulk_tissue_expression)

Download the file named: **`GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct.gz`**. This file contains the median gene-level TPM (Transcripts Per Million) by tissue. The median expression values were calculated from the file `GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz`. The file size is 6.6 MB.

In [9]:
import pandas as pd 
med_exp = pd.read_csv('human_genes_expression_pit/created_by_me/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct', sep='\t', skiprows= 2) # path_to_change
med_exp = med_exp[['Name', 'Pituitary', 'Description']]
med_exp['gene_id'] = med_exp['Name'].apply(lambda x: x.split('.')[0])
med_exp = med_exp.drop_duplicates(subset=['gene_id'])
med_exp

                    Name     Pituitary  Description          gene_id
0      ENSG00000223972.5      0.000000      DDX11L1  ENSG00000223972
1      ENSG00000227232.5      5.425460       WASH7P  ENSG00000227232
2      ENSG00000278267.1      0.000000    MIR6859-1  ENSG00000278267
3      ENSG00000243485.5      0.000000  MIR1302-2HG  ENSG00000243485
4      ENSG00000237613.2      0.000000      FAM138A  ENSG00000237613
...                  ...           ...          ...              ...
56195  ENSG00000198695.2   2028.050000       MT-ND6  ENSG00000198695
56196  ENSG00000210194.1      3.642400        MT-TE  ENSG00000210194
56197  ENSG00000198727.2  19925.500000       MT-CYB  ENSG00000198727
56198  ENSG00000210195.2      0.000000        MT-TT  ENSG00000210195
56199  ENSG00000210196.2      0.575686        MT-TP  ENSG00000210196

[56156 rows x 4 columns]

In [12]:
final_df = pd.merge(df, med_exp, left_on='last_gene_id', right_on='Description', how='inner')
final_df

,seqname,source,feature,start,end,score,strand,frame,last_gene_id,transcript_id,...,12S,16S,transl_table,ATPase,GENE_ID,sequence,Name,Pituitary,Description,gene_id
0,NC_000001.11,,gene,11874,14409,NaN,+,0,DDX11L1,,...,,,,,DDX11L1,CTTGCCGTCAGCCTTTTCTTTGACCTCTTCTTTCTGTTCATGTGTA...,ENSG00000223972.5,0.00000,DDX11L1,ENSG00000223972
1,NC_000001.11,,gene,14362,29370,NaN,-,0,WASH7P,,...,,,,,WASH7P,AAATCCCATTACAAATGGGGTGACTGAAGCTCCATTCATGGCTTGC...,ENSG00000227232.5,5.42546,WASH7P,ENSG00000227232
2,NC_000001.11,,gene,17369,17436,NaN,-,0,MIR6859-1,,...,,,,,MIR6859-1,ACCATCCCACATCCTCCCCCTCCCTTTCCTCATGAACCCCAGTCGC...,ENSG00000278267.1,0.00000,MIR6859-1,ENSG00000278267
3,NC_000001.11,,gene,29774,35418,NaN,+,0,MIR1302-2HG,,...,,,,,MIR1302-2HG,tgccctccagccctaCGCCTTGACCCGCTTTCCTGCGTCTCTCAGC...,ENSG00000243485.5,0.00000,MIR1302-2HG,ENSG00000243485
4,NC_000001.11,,gene,34611,36081,NaN,-,0,FAM138A,,...,,,,,FAM138A,CTCCTGTCAAACCCACGTGGAAGGCAGGCTCTGGGCTGTGTTACTG...,ENSG00000237613.2,0.00000,FAM138A,ENSG00000237613
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34682,NC_000024.10,,gene,26563992,26579868,NaN,+,0,TPTE2P4,,...,,,,,TPTE2P4,tttcttttttactgttatccaaaaaaattataaaagacatGAATTG...,ENSG00000215506.5,0.00000,TPTE2P4,ENSG00000215506
34683,NC_000024.10,,gene,26586445,26587563,NaN,-,0,SLC25A15P1,,...,,,,,SLC25A15P1,AAGGCAGAGGTTGAAGTGAGTGAAGATTGTGCCATTACACTCCAGC...,ENSG00000227629.1,0.00000,SLC25A15P1,ENSG00000227629
34684,NC_000024.10,,gene,26594668,26634655,NaN,-,0,PARP4P1,,...,,,,,PARP4P1,AAGCAAAGGATCTGGAATTTGTAAGGCTTAGCTTTGAATTCTTGCT...,ENSG00000237917.1,0.00000,PARP4P1,ENSG00000237917
34685,NC_000024.10,,gene,56855243,56856370,NaN,+,0,CTBP2P1,,...,,,,,CTBP2P1,aagaaactgtgtgAACAAGGAATTCTTTGTCACATCTGTGCTTTGG...,ENSG00000235857.1,0.00000,CTBP2P1,ENSG00000235857
34686,NT_187562.1,,gene,311143,311575,NaN,+,0,TRBV6-2,,...,,,,,TRBV6-2,ATGAGCCTCGGGCTCCTGTGCTGTGGGGCCTTTTCTCTCCTGTGGG...,ENSG00000283063.1,0.00000,TRBV6-2,ENSG00000283063